"""empty message

Revision ID: 914c5a41e2c3
Revises: 8ae47f642e4e
Create Date: 2021-01-21 16:29:00.889036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '914c5a41e2c3'
down_revision = '8ae47f642e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('path', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
