#For development
version: '3'
services:
    app:
        container_name: app
        image: mgkdb:latest
        ports:
            - "5000:5000"
        links:
            - mysql:dbserver
    mysql:
        container_name: db
        image: mysql:latest
        volumes: 
            - db-data:/var/lib/mysql
        env_file: DB/.env-mysql
        cap_add:
            - SYS_NICE
    # nginx:
    #     container_name: nginx
    #     image: nginx:latest
    #     ports:
    #         - 1337:8081
    #     depends_on:
    #         - app
volumes:
    db-data: