FROM python:3.7-stretch

# Install Python and Package Libraries
RUN apt-get update && apt-get upgrade -y && apt-get autoremove && apt-get autoclean
RUN apt-get install -y \
curl \
cron \
vim

RUN mkdir /app
COPY ./MGKDB-Web /app
COPY ./requirements.txt /app

WORKDIR /app

RUN pip install -r /app/requirements.txt 